- hosts: localhost
  collections:
    - netapp.storagegrid
  vars_files:
    /root/git/sg_vars.yml


- name: Get user authorization token
  uri:
    url: "{{ grid_admin_base_url }}/api/v3/authorize"
    method: POST
    body: {
      "accountId": "{{ account.resp.id }}",
      "username": "{{ tenant_user }}",
      "password": "{{ tenant_pass }}",
      "cookie": false,
      "csrfToken": false
    }
    body_format: json
    validate_certs: false
  register: auth